[kijanikiosk]
api-staging ansible_host=10.139.243.128
payments-staging ansible_host=10.139.243.105
logs-staging ansible_host=10.139.243.140

[kijanikiosk:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_ed25519
